# Generated by Django 2.0 on 2017-12-13 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abcsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='site', editable=False, max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('a_value', models.FloatField(default=0.0)),
                ('b_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Demosite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='site', editable=False, max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('a_value', models.FloatField(default=0.0)),
                ('b_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Xyzsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='site', editable=False, max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('a_value', models.FloatField(default=0.0)),
                ('b_value', models.FloatField(default=0.0)),
            ],
        ),
    ]
