# Generated by Django 2.0 on 2017-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcsite',
            name='site_name',
            field=models.CharField(default='site', max_length=20),
        ),
        migrations.AlterField(
            model_name='demosite',
            name='site_name',
            field=models.CharField(default='site', max_length=20),
        ),
        migrations.AlterField(
            model_name='xyzsite',
            name='site_name',
            field=models.CharField(default='site', max_length=20),
        ),
    ]
