# Generated by Django 2.0 on 2017-12-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20171213_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abcsite',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='demosite',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='xyzsite',
            name='site_name',
        ),
    ]
