# Generated by Django 2.0 on 2017-12-14 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20171213_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcsite',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demosite',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='xyzsite',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
