# Generated by Django 2.0 on 2017-12-14 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20171214_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcsite',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='demosite',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='xyzsite',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
