# Generated by Django 2.0 on 2017-12-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20171214_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcsite',
            name='a_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='abcsite',
            name='b_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='demosite',
            name='a_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='demosite',
            name='b_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='xyzsite',
            name='a_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='xyzsite',
            name='b_value',
            field=models.FloatField(default=0.0),
        ),
    ]
